### ISSUE TITLE
[下载]官网下载发生“无法安全下载”的问题

### ISSUE THREAD

**Issue by zhuyc110** [acely/Arctime-Pro#19]
目前Arctime Pro官网是HTTPS链接的，但是下载页面中的下载链接全部是HTTP的。
如：_http_://dl.arctime.cn/ARCTIME_PRO_3.1.1_WIN32.rar

这导致在EDGE（版本 96.0.1054.43 (官方内部版本) (64 位)）上进行下载时，会有如下提示：
![image](https://user-images.githubusercontent.com/8545052/145658864-5a469eec-cf5e-4d0a-ab01-2c090c21a4c8.png)

具体原因可以参考此[微软文档](https://docs.microsoft.com/en-us/DeployEdge/edge-learnmore-mixed-content-downloads)。

**Comment by acely** [comment]
可以尝试官网提供的其他备用链接
