### ISSUE TITLE
对字幕块批量操作

### ISSUE THREAD

**Issue by gameclamp** [acely/Arctime-Pro#2]
![qq 20170921222343](https://user-images.githubusercontent.com/1432607/30700932-96f785ac-9f1b-11e7-839e-94392b15891d.png)
例如选中多个字幕块，同时设置他们的分组或者样式。

**Comment by acely** [comment]
好的，这个非常实用，也有必要

**Comment by acely** [comment]
2.1版开始已支持此功能
