### ISSUE TITLE
希望能改成调用系统的java

### ISSUE THREAD

**Issue by tao-bioinfo** [acely/Arctime-Pro#20]
特别是Mac，java17是支持arm芯片的。现在的版本在mac上很卡

**Comment by acely** [comment]
arctime集成的jre、vlc等组件是联合调教好的一个整体，都是经过兼容性优化和全面测试的，不能粗暴的单独更换某一部分，不然很可能造成兼容性问题甚至无法启动。
不过我们已经在准备兼容arm的版本了，还请等待。

**Comment by tao-bioinfo** [comment]
> arctime集成的jre、vlc等组件是联合调教好的一个整体，都是经过兼容性优化和全面测试的，不能粗暴的单独更换某一部分，不然很可能造成兼容性问题甚至无法启动。
> 不过我们已经在准备兼容arm的版本了，还请等待。

那只能希望arm版本尽快出来了
